//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JComment: IDbElement<JComment>
    {
        public int id { get; set; }
        public string text { get; set; }
        public int eventId { get; set; }
        public int userId { get; set; }
        public Nullable<int> parentId { get; set; }
    
        public virtual JEvent JEvent { get; set; }
        public virtual JEvent JEvent1 { get; set; }
        public virtual JUser JUser { get; set; }
    }
}
