//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JEventStatu: IDbElement<JEventStatu>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JEventStatu()
        {
            this.JEvents = new HashSet<JEvent>();
        }
    
        public int id { get; set; }
        public string eventStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JEvent> JEvents { get; set; }
    }
}
