//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFContext.Models
{
    using EFContext.Models;
    using System;
    using System.Collections.Generic;
    
    public partial class JEvent: IDbElement<JEvent>,ICloneable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JEvent()
        {
            this.JComments = new HashSet<JComment>();
            this.JComments1 = new HashSet<JComment>();
            this.JEvent1 = new HashSet<JEvent>();
            this.JProjects = new HashSet<JProject>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> openBy { get; set; }
        public System.DateTime dueDate { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> parentEvent { get; set; }
        public int eventType { get; set; }
        public int eventStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JComment> JComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JComment> JComments1 { get; set; }
        public virtual JEventStatu JEventStatu { get; set; }
        public virtual JEventType JEventType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JEvent> JEvent1 { get; set; }
        public virtual JEvent JEvent2 { get; set; }
        public virtual JUser JUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JProject> JProjects { get; set; }

        public object Clone()
        {
            var x = this;
            x.name = "test";
            return x;
        }
    }
}
