//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace EFContext.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Jira_DatabaseEntities1 : DbContext
    {
        public Jira_DatabaseEntities1()
            : base("name=Jira_DatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JComment> JComments { get; set; }
        public virtual DbSet<JEvent> JEvents { get; set; }
        public virtual DbSet<JEventStatu> JEventStatus { get; set; }
        public virtual DbSet<JEventType> JEventTypes { get; set; }
        public virtual DbSet<JProject> JProjects { get; set; }
        public virtual DbSet<JTeam> JTeams { get; set; }
        public virtual DbSet<JTeamUser> JTeamUsers { get; set; }
        public virtual DbSet<JUser> JUsers { get; set; }
        public virtual DbSet<JUserType> JUserTypes { get; set; }
    }
}
