//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiraApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JTeamUser
    {
        public int userId { get; set; }
        public int teamId { get; set; }
        public bool isLead { get; set; }
    
        public virtual JTeam JTeam { get; set; }
        public virtual JUser JUser { get; set; }
    }
}
